apiVersion: v1
kind: Secret
type: Opaque
data:
  credentials: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gQUtJQVpRUTdMVFdCSkxYRVdTRUYKYXdzX3NlY3JldF9hY2Nlc3Nfa2V5ID0gK1NKWlhFYVpsajdDcktmTTZQMXNBTWhDVGUzR25EVU54TjRjVnhHSwo=
metadata:
  name: aws-secret